import frappe


def on_contract_submit(doc, method=None):
	"""Called when Contract docstatus → 1 (Submitted)."""
	if doc.party_type != "Customer":
		return
	if not doc.get("mz_service_lines"):
		return
	_setup_subscription(doc)


def on_contract_status_change(doc, method=None):
	"""Called on on_update_after_submit when mz_service_status changes."""
	status = doc.get("mz_service_status")
	if status == "Suspended":
		_pause_subscription(doc)
	elif status == "Deactivated":
		_cancel_subscription(doc)
	elif status == "Active":
		_resume_subscription(doc)


def on_invoice_submit(doc, method=None):
	"""Tag Sales Invoice when generated by an MZ SaaS Subscription."""
	if not doc.subscription:
		return

	contract = frappe.db.get_value(
		"Contract", {"mz_linked_subscription": doc.subscription}, "name"
	)
	if not contract:
		return

	sales_responsible = frappe.db.get_value("Contract", contract, "mz_sales_responsible")

	doc.db_set("mz_saas_managed", 1)
	doc.db_set("mz_contract", contract)

	if sales_responsible:
		responsible_email = frappe.db.get_value("User", sales_responsible, "email")
		if responsible_email:
			doc.db_set("mz_sales_responsible_email", responsible_email)


def _setup_subscription(doc):
	"""Create an ERPNext Subscription from the contract's mz_service_lines."""
	if not frappe.db.exists("DocType", "Subscription"):
		frappe.log_error(
			title="MZ SaaS: Subscription DocType Not Found",
			message="ERPNext Accounts module may not be installed.",
		)
		return

	plans = []
	for line in doc.mz_service_lines:
		if not line.service_plan:
			continue
		linked_plan = frappe.db.get_value("MZ SaaS Plan", line.service_plan, "linked_subscription_plan")
		if not linked_plan:
			frappe.log_error(
				title=f"MZ SaaS: No linked Subscription Plan for {line.service_plan}",
				message=f"Contract: {doc.name} — Save the MZ SaaS Plan first to auto-create the Subscription Plan.",
			)
			continue
		plans.append({
			"plan": linked_plan,
			"qty": line.quantity or 1,
		})

	if not plans:
		frappe.log_error(
			title="MZ SaaS: No valid Subscription Plans to create Subscription",
			message=f"Contract: {doc.name}",
		)
		return

	sub = frappe.get_doc({
		"doctype": "Subscription",
		"party_type": "Customer",
		"party": doc.party_name,
		"start_date": doc.start_date,
		"end_date": doc.end_date or None,
		"generate_invoice_at": "Beginning of the current subscription period",
		"plans": plans,
	})
	sub.insert(ignore_permissions=True)
	sub.submit()

	frappe.db.set_value("Contract", doc.name, "mz_linked_subscription", sub.name)
	frappe.db.set_value("Contract", doc.name, "mz_service_status", "Active")
	frappe.db.commit()


def _pause_subscription(doc):
	"""Pause (cancel) the linked ERPNext Subscription."""
	sub_name = doc.get("mz_linked_subscription")
	if not sub_name:
		return
	try:
		sub = frappe.get_doc("Subscription", sub_name)
		if sub.docstatus == 1:
			sub.cancel()
	except Exception:
		frappe.log_error(
			title=f"MZ SaaS: Failed to pause Subscription {sub_name}",
			message=frappe.get_traceback(),
		)


def _cancel_subscription(doc):
	"""Cancel the linked ERPNext Subscription."""
	_pause_subscription(doc)


def _resume_subscription(doc):
	"""Re-create the subscription when contract is reactivated."""
	_setup_subscription(doc)
